### PR TITLE
Smaller tables

### LINKED ISSUE #101: Reduce load of Dynamic SID allocation
Today, an "lb_timeout" parameter tells LBs how long they need to save an SID allocation after it's last observed on an incoming packet. Servers may have to retire CIDs when they're approaching this limit. It's the only current method of getting rid of these, as we lack any sort of in-band mechanism for the two entities to communicate.

Advantages:
- servers have more SIDs to choose from, which dramatically improves the entropy of PCID (where, admittedly, the operator has chosen not to care about concealing the mapping)
- the server is seldom compelled to retire active CIDs, so the overhead of NEW/RETIRE_CONNECTION_ID frames is low

Disadvantages:
- If the server ID space >> the number of servers, over time the LB's table gets very large, to the extent it could challenge the RAM of the device. Careful selection of a server ID length can help, but that's putting a lot on the operator.
- The lb_timeout mechanism is annoying because LBs that store a little bit of state have to inspect every packet to make a note of the last time it observed an SID. Servers have to do the same to check when things expire. This seems easy to mess up.
- Servers also have to decode every incoming Initial CID to extract the SID.

An alternative would configure servers to keep a small number of SIDs. This could be as low as 1 but might be 8 or 16. If an allocatable SID arrives at the server, if it does not *instantly* use that SID in the CID it sends with the server hello, it forfeits the allocation.

Example of acceptance:
- SID 0x14 arrives in a Client Initial. LB hashes it to a server and adds it to a hash table of provisional allocations
- Server generates CID using 0x14 and sends it the Server Initial, adding it to its list of server IDs
- LB notes that the first inbound short header encoded 0x14 and makes it a permanent allocation

Example of rejection
-  SID 0x15 arrives in a Client Initial. LB hashes it to a server and adds it to a hash table of provisional allocations
-  Other long headers with 0x15, with any 4-tuple, also go to the server thanks to the provisional list (you can't be provisional to two servers!)
- Server generates a CID that encodes 0x14.
- LB notes that the first inbound short header did not encode 0x15 and decrements the ref count for the provisional allocation, deleting it if the ref count is zero.

We could even make it so the server MUST accept the first n that it can; then, the LB need not even do a provisional allocation after that peer has reached the threshold.

Advantages:
- much fewer resources for SID tables
- no timers, less CID parsing & inspection
- the architecture doesn't mandate more CID retiring due to changing SIDs

Disadvantages:
- ?

### PR DESCRIPTION
**Pull request by martinduke**
Fixes #101. This tweak, IMO, substantially improves dynamic allocation.

### CODE REVIEW

**Comment by martinduke** [comment]
@ianswett I believe this is good as dynamic SID allocation is going to get, so IMO this is a strict improvement on the current text.

However, I'd like you to review it, as the drawbacks remain significant and if you're no longer wedded to this approach it might best be removed. It's true that SID allocation is kind of a pain, but even with dynamic allocation the LB still needs to configure its server pool, so the gains are not all that large.

Also adding @huitema due to a heinous hack involving zero padding short CIDs, that I can't seem to poke a security hole in.

**Review by ianswett — APPROVED** [review]
LG, though the more I think about this, the more I want to just move away from this approach. In retrospect, I think it's just a bit too clever for our own good.

**Review by huitema — COMMENTED** [review]
I am kind of convinced that "padding with zeroes" will not end well. I am also a tiny bit worried that relying on the values provided in initial packets for dynamic allocations will backfire when clients become creative. The spec says "When an Initial packet is sent by a client that has not previously received an Initial or Retry packet from the server, the client populates the Destination Connection ID field with an unpredictable value. This Destination Connection ID MUST be at least 8 bytes in length." But "unpredictable value" is in the eyes of the beholder, and "99999999" is just as unpredictable as "012345678".

I would feel better if the dynamic method was only used in conjunction with stream encryption and length 8 CID, because clients will have a hard time predicting what an arbitrary CID decrypts to: flip one bit in the input, and every output bit has a 50% chance of splitting. The block cipher might also work, but will definitely require padding.

**Comment by martinduke** [comment]
thanks, will merge this as a strict improvement (zero padding is bad but better than "read a bunch of bytes as if was plaintext"), then take up the issue of whether to keep dynamic at all.

**Pull request merged**
